### ISSUE TITLE
Configurable sailsd host/port

### ISSUE THREAD

**Issue by joshes** [sails-simulator/python-sailsd#2]
I'd like to be able to configure the sailsd host & port dynamically, defaulting to 'localhost' and '3333'. What would be the preferred method?

I've put together a quick PR for a simple constructor arg based fix. Happy to change it as desired (environment vars, etc).

**Comment by joshes** [comment]
Thanks for the merge. As this is a non-breaking change, how does one make it available via `pip`?

**Comment by kragniz** [comment]
I'll need to cut a new release for it to be available via pypi, in the meantime you should be able to reference the git repo and commit hash something like:

    pip install git+https://github.com/sails-simulator/python-sailsd.git@53f7f3d

**Comment by joshes** [comment]
Cool, thank-you & def no rush. Just piping this into my Docker images and makes it just a touch simpler after the fact.

**Comment by kragniz** [comment]
Is your docker stuff public anywhere? For boatd I started https://github.com/boatd/boatd-development-environment but didn't end up using it anywhere

**Comment by joshes** [comment]
Not ATM. I'm considering the options - and hadn't seen that repo until now; I wanted to keep it modular and pull it all together in docker-compose vs a monolithic Dockerfile (which frankly is simpler, but less flexible long-term). 

What I have ATM looks like this:

```
$ tree
.
├── docker-boatd
│   ├── Dockerfile
│   ├── basic-behaviour.py
│   ├── boatd-config.yaml
│   └── example-driver.py
├── docker-compose.yml
├── docker-libsailing
│   └── Dockerfile
├── docker-sails-boatd-driver
│   ├── Dockerfile
│   └── boatd-config.yaml
├── docker-sails-ui-web
│   └── Dockerfile
└── docker-sailsd
    └── Dockerfile
```

And ultimately the `docker-compose.yml` looks like this:

```
version: '3'
services:
  boatd:
    build: ./docker-sails-boatd-driver
    image: simboat/sails-boatd-driver:latest
    ports:
    - 2222:2222
  sailsd:
    build: ./docker-sailsd
    image: simboat/sailsd:latest
    ports:
    - 3333:3333
    depends_on:
    - boatd
  ui:
    build: ./docker-sails-ui-web
    image: simboat/sails-ui-web:latest
    environment:
      SAILSD_HOST: sailsd
      SAILSD_PORT: 3333
    links:
      - sailsd
    ports:
    - 8080:8080
    depends_on:
    - sailsd
```

This is nice and lets me work on configurations with a simple volume mapping. It's a work in progress, but feels OK so far. The Dockerfiles are just cloning the git repos, using Docker's multi-stage builds to keep things lean. So far, so good. Happy to share; would be good to figure out the best way to do so - either via Dockerfiles per project or a single mono-repo for the above directory layout.
